apiVersion: batch/v1
kind: Job
metadata:
  name: containerlimits
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  
  template:
    spec:
      containers:
      - name: containerlimits
        image: public.ecr.aws/zinclabs/container_limits:f441e90
        resources:
          limits:
            cpu: "2.5"
            memory: "2.5Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: gke-alpha-1-default-172688e3-07cz
